"""
Markdown 리포트 조립
7개 분석 결과를 iPad 호환 평문 마크다운 한 장으로 조립
블로그 게시용 복사 붙여넣기 가능 형식
"""
from datetime import datetime
from pathlib import Path


def build_report(
    stock_code: str,
    company_name: str,
    sector: str,
    raw_data: dict,
    metrics: dict,
    ai_results: dict,
) -> str:
    """Markdown 전체 리포트 조립"""

    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    parts = []

    # 헤더
    parts.append(f"# {company_name} ({stock_code}) DART 종합 분석")
    parts.append(f"**업종**: {sector}  ")
    parts.append(f"**분석일시**: {now}  ")
    parts.append(f"**데이터 출처**: DART 전자공시 + Gemini 분석")
    parts.append("\n---\n")

    # 정량 사전계산 요약 (Gemini 분석 검증용)
    parts.append("## 📊 정량 지표 사전계산 (Python 검증값)")
    parts.append("> Gemini 분석의 정확성 검증을 위해 Python에서 직접 계산한 핵심 지표\n")

    # 불곰 안전성 결과
    if metrics.get("bulgom"):
        b = metrics["bulgom"]
        parts.append("### 불곰 재무 안전성 (6개 항목 자동 판정)")
        parts.append(f"**판정**: {b.get('판정', '-')} ({b.get('passed_count', 0)}/{b.get('total', 6)} 통과)\n")
        parts.append("| 항목 | 기준 | 실제값 | 통과 |")
        parts.append("|------|------|--------|------|")
        for name, check in b.get("checks", {}).items():
            val = check.get("value", check.get("values", "-"))
            pass_mark = "✅" if check.get("pass") else "❌"
            parts.append(f"| {name} | {check.get('기준', '-')} | {val} | {pass_mark} |")
        parts.append("")

    # 카츠미 지표
    if metrics.get("katsuma"):
        parts.append("### 카츠미 핵심 지표 (5년 추이)")
        years = sorted(metrics["katsuma"].keys())
        if years:
            parts.append("| 연도 | 영업CF/영업이익 | 회수개월수 | 회계발생고비율 | ROA | 영업이익률 | CF패턴 |")
            parts.append("|------|---------------|----------|-------------|-----|----------|--------|")
            for y in years:
                m = metrics["katsuma"][y]
                row = f"| {y} | "
                row += f"{m.get('영업CF_영업이익_비율'):.1f}% | " if m.get('영업CF_영업이익_비율') else "- | "
                row += f"{m.get('회수개월수'):.2f}개월 | " if m.get('회수개월수') else "- | "
                row += f"{m.get('회계발생고_비율'):.1f}% | " if m.get('회계발생고_비율') else "- | "
                row += f"{m.get('ROA'):.2f}% | " if m.get('ROA') else "- | "
                row += f"{m.get('영업이익률'):.2f}% | " if m.get('영업이익률') else "- | "
                row += f"{m.get('CF패턴', '-')} |"
                parts.append(row)
        parts.append("")

    # 성장률
    if metrics.get("growth", {}).get("CAGR"):
        parts.append("### 5년 CAGR")
        cagr = metrics["growth"]["CAGR"]
        for metric, value in cagr.items():
            parts.append(f"- {metric}: **{value}%**")
        parts.append("")

    parts.append("\n---\n")

    # Gemini 분석 결과 (7개 영역)
    module_titles = {
        "basic": "## 1️⃣ 기본 분석",
        "tenbagger": "## 2️⃣ 텐배거 탐지",
        "swing": "## 3️⃣ 단타/스윙 분석",
        "longterm": "## 4️⃣ 장기투자 분석",
        "bulgom": "## 5️⃣ 불곰식 6단계",
        "katsuma": "## 6️⃣ 카츠미 7대 체크리스트",
        "scenario": "## 7️⃣ 상승 시나리오 (5단계 탑다운)",
        "final": "## 🎯 최종 종합판정",
    }

    for key in ["basic", "tenbagger", "swing", "longterm", "bulgom", "katsuma", "scenario", "final"]:
        if ai_results.get(key):
            parts.append(module_titles[key])
            parts.append("")
            parts.append(ai_results[key])
            parts.append("\n---\n")

    # 푸터
    parts.append(f"\n*Generated by DART Analyzer at {now}*")

    return "\n".join(parts)


def save_report(content: str, stock_code: str, reports_dir: Path) -> Path:
    """리포트 파일 저장"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{stock_code}_{timestamp}.md"
    filepath = reports_dir / filename
    filepath.write_text(content, encoding="utf-8")
    return filepath
